/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface DemoParent {

    }
  }

  interface HTMLDemoParentElement extends StencilComponents.DemoParent, HTMLStencilElement {}

  var HTMLDemoParentElement: {
    prototype: HTMLDemoParentElement;
    new (): HTMLDemoParentElement;
  };
  interface HTMLElementTagNameMap {
    'demo-parent': HTMLDemoParentElement;
  }
  interface ElementTagNameMap {
    'demo-parent': HTMLDemoParentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'demo-parent': JSXElements.DemoParentAttributes;
    }
  }
  namespace JSXElements {
    export interface DemoParentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface OnClickOutside {

    }
  }

  interface HTMLOnClickOutsideElement extends StencilComponents.OnClickOutside, HTMLStencilElement {}

  var HTMLOnClickOutsideElement: {
    prototype: HTMLOnClickOutsideElement;
    new (): HTMLOnClickOutsideElement;
  };
  interface HTMLElementTagNameMap {
    'on-click-outside': HTMLOnClickOutsideElement;
  }
  interface ElementTagNameMap {
    'on-click-outside': HTMLOnClickOutsideElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'on-click-outside': JSXElements.OnClickOutsideAttributes;
    }
  }
  namespace JSXElements {
    export interface OnClickOutsideAttributes extends HTMLAttributes {
      'onClickoutside'?: (event: CustomEvent<{ sourceEvent: Event }>) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;